// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzM0Ti3dZ6kfX3QL1eiYgPQQL-fH_P5AA',
    appId: '1:773203331467:web:40df463ca2cfa9a095878e',
    messagingSenderId: '773203331467',
    projectId: 'samvya-cbaa8',
    authDomain: 'samvya-cbaa8.firebaseapp.com',
    storageBucket: 'samvya-cbaa8.firebasestorage.app',
    measurementId: 'G-W12Z5KZC4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOEWxrPpFob0Scb1wV1FudC38ZZeLBkO0',
    appId: '1:773203331467:android:17e9ff3a710d29c695878e',
    messagingSenderId: '773203331467',
    projectId: 'samvya-cbaa8',
    storageBucket: 'samvya-cbaa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VMVRfGqLAp-e_F_STU7g-kexvg4woSQ',
    appId: '1:773203331467:ios:a219d16c91a0b78595878e',
    messagingSenderId: '773203331467',
    projectId: 'samvya-cbaa8',
    storageBucket: 'samvya-cbaa8.firebasestorage.app',
    iosBundleId: 'com.example.samvya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VMVRfGqLAp-e_F_STU7g-kexvg4woSQ',
    appId: '1:773203331467:ios:a219d16c91a0b78595878e',
    messagingSenderId: '773203331467',
    projectId: 'samvya-cbaa8',
    storageBucket: 'samvya-cbaa8.firebasestorage.app',
    iosBundleId: 'com.example.samvya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzM0Ti3dZ6kfX3QL1eiYgPQQL-fH_P5AA',
    appId: '1:773203331467:web:774ac25e5f683d5595878e',
    messagingSenderId: '773203331467',
    projectId: 'samvya-cbaa8',
    authDomain: 'samvya-cbaa8.firebaseapp.com',
    storageBucket: 'samvya-cbaa8.firebasestorage.app',
    measurementId: 'G-7Z5PNM3GFF',
  );
}
